language: python
python:
  - 3.5
addons:
  apt:
    packages:
      - portaudio19-dev
script:
  - make
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
after_success:
  - pip install python-coveralls && coveralls
